### PR TITLE
#161967121 Integrate Coveralls 

### PR DESCRIPTION
**Pull request by davishooly**
### What does this PR do?
  - integrates coveralls with Authors Haven Django App
<hr>

### Description of Task to be completed?
  - Have coverage sent to coverall after successful Travis build
  - Add coverage badge to ReadMe
<hr>

### How should this be manually tested?
   - No tests required
<hr>

### What are the relevant pivotal tracker stories?
[ #161967121 ](https://www.pivotaltracker.com/story/show/161967121)
<hr>

### Screenshots 
screen shot 2018-11-28 at 07 58 02

#### What are the relevant pivotal tracker stories?
  - [#161967118](https://www.pivotaltracker.com/story/show/161967118)
--------------

#### Checklist
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings

### CODE REVIEW

**Comment by bettblake08** [comment]
@davishooly In the readme markdown file, no new line between the badges. This allows the badges to be aligned side by side

**Review by bettblake08 — COMMENTED** [review]
The PR is all good.

**Comment by jillo-abdullahi** [comment]
@davishooly You can also add the checklist that @evansmusomi mentioned on Slack.

**Review by mutoromike — CHANGES_REQUESTED** [review]
The Coverage Badge is not working. Kindly fix it.

**Comment by denomash** [comment]
Good work @davishooly. Noted that badge is not indicating percentage in the repo. Look into it.

**Review by mutoromike — APPROVED** [review]

**Review by jillo-abdullahi — APPROVED** [review]

**Pull request merged**
