### PR TITLE
#161967128 Enable social media login backend

### PR DESCRIPTION
**Pull request by bettblake08**
#### What does this PR do?
Integrate social media login using Facebook, Twitter and Google Plus APIs.

#### Description of Task to be completed?
- Create the social media login endpoint
- Add tests for social media login endpoint

#### How should this be manually tested?
- Clone the repo and cd into the project folder
- Create a virtual environment by running `$ python3 -m venv <name_of_environment>`
- Activate the virtual environment by running `source <name_of_environment>/bin/activate`
- Run `$ pip install -r requirements.txt`
- Then add the following environment variables to your computer.

    - `$ export DB_NAME='choose_a_dbname'`
    - `$ export DB_USER='db_username'`
    - `$ export DB_PASSWORD='db_role_password'`
    - `$ export DB_HOST='localhost or preffered host'`
    - `$ export DB_PORT='server_port_number'`
    - `$ export SECRET_KEY="secret_key"`
    - `$ export SOCIAL_AUTH_FACEBOOK_KEY='<facebook_app_id>'`
    - `$ export SOCIAL_AUTH_FACEBOOK_SECRET='<facebook_app_secret>'`
    - `$ export SOCIAL_AUTH_TWITTER_KEY='<twitter_api_key>'`
    - `$ export SOCIAL_AUTH_TWITTER_SECRET='<twitter_api_secret>'`
    - `$ export SOCIAL_AUTH_GOOGLE_OAUTH2_KEY='<google_client_id>'`
    - `$ export SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET='<google_client_secret>'`

- Change the current branch to ft-social-login-backend-161967128
- Run ..
   - `python manage.py makemigrations`
   - `python manage.py migrate`
   - `python manage.py test`

#### What are the relevant pivotal tracker stories?
[#161967128](https://www.pivotaltracker.com/story/show/161967128)

#### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by denomash** [comment]
In the PR export `SECRET_KEY` in the environment variables.

**Comment by bettblake08** [comment]
> In the PR export `SECRET_KEY` in the environment variables.

@denomash Thanks. I've added it!

**Review by jillo-abdullahi — COMMENTED** [review]
Hi, @bettblake08 Tests ran the first time but now it looks like the Google access_token is expired. I get this error: `social_core.exceptions.AuthForbidden: Your credentials aren't allowed` for `test_google_endpoint`

**Review by mutoromike — CHANGES_REQUESTED** [review]
Fix tests and merge conflicts.

**Comment by bettblake08** [comment]
@mutoromike I fixed the Travis CI bug that was causing tests to fail. I have also resolved the merge conflicts with the current develop branch.

**Pull request closed without merging**
