### PR TITLE
#161967149 User read statistics

### PR DESCRIPTION
**Pull request by davishooly**
**What does this PR do?**
-  Implements user read statics

**Description of Task to be completed?**
- authenticated users can view articles that they have read.

**How should this be manually tested?**

- Clone the repo and cd into the project folder
- Create a virtual environment by running `python3 -m venv <name_of_environment>`
- Activate the virtual environment by running `source <name_of_environment>/bin/activate`
- Run `$ pip install -r requirements.txt`
- Then add the following environment variables to your computer:

 - `$ export DB_NAME='choose_a_dbname'`
 - `$ export DB_USER='db_username'`
 - `$ export DB_PASSWORD='db_role_password'`
 - `$ export DB_HOST='localhost or preffered host'`
 - `$ export DB_PORT='server_port_number'`
- `$ export SECRET_KEY='some_secret_key`
- `$ export SOCIAL_AUTH_FACEBOOK_KEY='<facebook_app_id>'`
- `$ export SOCIAL_AUTH_FACEBOOK_SECRET='<facebook_app_secret>'`
- `$ export SOCIAL_AUTH_TWITTER_KEY='<twitter_api_key>'`
- `$ export SOCIAL_AUTH_TWITTER_SECRET='<twitter_api_secret>'`
- `$ export SOCIAL_AUTH_GOOGLE_OAUTH2_KEY='<google_client_id>'`
- `$ export SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET='<google_client_secret>'`

- Change the current branch by running `git checkout  ft-read-stats-161967149`
- Run `python3 manage.py makemigrations` then, `python3 manage.py migrate`
- Run `python3 manage.py runserver`

-  fetching an article endpoint:
**GET** `article/javascript-es9`

-  marking an article as read by a user:
**GET** `/read/javascript-es9`

- get all read articles of a specific user:
**GET** `/read-stats`

**What are the relevant pivotal tracker stories?**
- [#161967149](https://www.pivotaltracker.com/story/show/161967149)

**Checklist (edited)**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

**Screenshots **
screen shot 2018-12-21 at 12 14 42

screen shot 2018-12-21 at 12 15 46

### CODE REVIEW

**Review by jillo-abdullahi — APPROVED** [review]
👍

**Review by denomash — APPROVED** [review]
Works fine. 👍

**Review by bettblake08 — APPROVED** [review]
👍

**Review by Darius-Ndubi — APPROVED** [review]
👍

**Pull request merged**
