### PR TITLE
Pagination support for articles

### PR DESCRIPTION
**Pull request by Bryan-Cee**
**What does this PR do?**

**Description of Task to be completed?**

- Add pagination support for articles.
- Add test for pagination.

**How should this be manually tested?**

- Clone the repo and cd into the project folder
- Create a virtual environment by running $ python3 -m venv <name_of_environment>
- Activate the virtual environment by running source <name_of_environment>/bin/activate
- Run $ pip install -r requirements.txt
- Then add the following environment variables to your computer.

```
$ export DB_NAME='choose_a_dbname'
$ export DB_USER='db_username'
$ export DB_PASSWORD='db_role_password'
$ export DB_HOST='localhost or preffered host'
$ export DB_PORT='server_port_number'
$ export APP_DEBUG='True'
$ export SOCIAL_AUTH_FACEBOOK_KEY='<facebook_app_id>'
$ export SOCIAL_AUTH_FACEBOOK_SECRET='<facebook_app_secret>'
$ export SOCIAL_AUTH_TWITTER_KEY='<twitter_api_key>'
$ export SOCIAL_AUTH_TWITTER_SECRET='<twitter_api_secret>'
$ export SOCIAL_AUTH_GOOGLE_OAUTH2_KEY='<google_client_id>'
$ export SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET='<google_client_secret>'
```

- Change the current branch to ft-pagination-support-161967140
- Run `python3 manage.py makemigrations`
- Run `python3 manage.py migrate`
- Run `python3 manage.py test`
- Run `python3 manage.py runserver`
- Test `http://localhost:8000/api/articles/all` with postman

**What are the relevant pivotal tracker stories?**
[#161967140](https://www.pivotaltracker.com/story/show/161967140)

**Screenshots**
screenshot 2018-12-18 at 14 18 57
screenshot 2018-12-18 at 14 19 45

**

### CODE REVIEW

**Review by davishooly — APPROVED** [review]

**Review by Darius-Ndubi — APPROVED** [review]
👍

**Review by denomash — APPROVED** [review]
👍

**Review by bettblake08 — APPROVED** [review]

**Review by jillo-abdullahi — APPROVED** [review]
lgtm 👍

**Review by mutoromike — CHANGES_REQUESTED** [review]
Could you make the limit and offset to be received from the user-end, and not hard-coded. This will make pagination from the front end much easier.

**Comment by Bryan-Cee** [comment]
@mutoromike The first default view is 10 articles but the limit and offset can be changed by the user by passing query parameters. This will be abstracted when developing the frontend.

screenshot 2018-12-18 at 14 19 26

**Review by mutoromike — APPROVED** [review]

**Pull request merged**
